inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-sequel

AllCops:
  NewCops: enable
  # Do not attempt to police vendored code
  Exclude:
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

# We prefer to use ”” by default and use ’’ to signal that interpolation is
# intentionally turned off, but we don't enforce it.
Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: true
  IgnoreCopDirectives: false
  Max: 120
  # Too much models have long lines, which is unsafe to reduce without
  # having an existing model unit test.
  Exclude:
   - lib/oxidized/model/*.rb

# We do not enforce the cop in the models as it would not work with the
# DSL style of the models
Lint/AmbiguousRegexpLiteral:
  Enabled: true
  Exclude:
   - lib/oxidized/model/*.rb

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# Stick to verbose until https://bugs.ruby-lang.org/issues/10177 is closed.
Style/PreferredHashMethods:
  EnforcedStyle: verbose

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Explicitly allow the use of "not"
Style/Not:
  Enabled: false

# comply with @ytti's exacting specifications
Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/ConditionalAssignment:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# Explicitly allow the use of rescue as a Modifier
Style/RescueModifier:
  Enabled: false

# Intentionally left deactivated as used in the models
Style/SymbolProc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: true

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# The BlockLength metric does not apply to unit tests. They are in nature
# long and not very pretty
Metrics/BlockLength:
  Max: 150
  Exclude:
   - spec/**/*_spec.rb

Metrics/ParameterLists:
  Max: 6

# Used in the models
Lint/EmptyBlock:
  Enabled: false

# Disable the cop as string concatenation is widely used in oxidized
Style/StringConcatenation:
  Enabled: false

