#!/bin/bash

gem uninstall oxidized-*
gem uninstall oxidized-ssh
gem build oxidized.gemspec
yes | gem install ./oxidized-0.19.0.gem --no-ri --no-rdoc
yes | gem install ../oxidized-web/oxidized-web-0.8.0.gem --no-ri --no-rdoc
yes | gem install ../oxidized-script/oxidized-script-0.3.1.gem --no-ri --no-rdoc
yes | gem install ../oxidized-ssh/oxidized-ssh-0.1.3.gem --no-ri --no-rdoc
