#!/bin/bash

yes | gem uninstall oxidized
yes | gem uninstall oxidized-ssh
rm ./oxidized-0.19.0.gem
rm ../oxidized-ssh/oxidized-ssh-0.1.3.gem
gem build oxidized.gemspec
yes | gem install ./oxidized-0.19.0.gem --no-ri --no-rdoc
cd ../oxidized-ssh
gem build oxidized-ssh.gemspec
yes | gem install oxidized-ssh-0.1.3.gem --no-ri --no-rdoc
