module Oxidized
  module Output
    # Handles the output processing for Oxidized.
    #
    # This class is responsible for formatting and managing the output
    # generated by various commands run against network devices.
    class Output
      require 'oxidized/error/noconfig'

      # Converts the provided configuration array to a string.
      #
      # @param cfg [Array<Hash>] An array of hashes, where each hash contains
      #   configuration details. Each hash should have a :type key indicating
      #   the type of configuration, and a :data key containing the configuration data.
      # @return [String] A concatenated string of all configuration data where
      #   the type is 'cfg'.
      def cfg_to_str(cfg)
        cfg.select { |h| h[:type] == 'cfg' }.map { |h| h[:data] }.join
      end
    end
  end
end
